apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.35.0 (HEAD)
  labels:
    io.kompose.service: service-b
  name: service-b
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: service-b
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.35.0 (HEAD)
      labels:
        io.kompose.service: service-b
    spec:
      containers:
        - image: service-b:latest
          name: service-b
          ports:
            - containerPort: 8082
              protocol: TCP
      restartPolicy: Always
